---
title: "Lab 2 - Introduction to RStudio Cont'd"
author: "Your Name"
date: "Date of lab session"
output:
  html_document:
    highlight: pygments
    theme: spacelab
  pdf_document: default
---

```{r setup, include=FALSE}
#install.packages("knitr")
library(knitr)
# DO NOT ALTER CODE IN THIS CHUNK
knitr::opts_chunk$set(echo = TRUE)
#install.packages("dplyr")
#library(dplyr)
#install.packages("ggplot2")
#library(ggplot2)
```

* * *

## Lab report

**Load Forbes94 data**
```{r}
Forbes94 = read.table("http://www2.stat.duke.edu/~oma9/STA111_SummerI_2016/Labs/Forbes94.txt",header=T)
```

#### Question 1: 

[Enter your response for Question 1 here.]

```{r}
# Enter your code for question 1 here

```

#### Question 2:

[Enter your response for Question 2 here.]

```{r}
# Enter your code for question 2 here
```


#### Question 3:

[Enter your response for Question 3 here.]

```{r}
# Enter your code for question 3 here
```


#### Question 4:

[Enter your response for Question 4 here.]

```{r}
# Enter your code for question 4 here
```


#### Question 5:

[Enter your response for Question 5 here.]

```{r}
# Enter your code for question 5 here
```


#### Question 6:

[Enter your response for Question 6 here.]

```{r}
# Enter your code for question 6 here
```


* * *



